name: 🐛 Bug
description: Qualcosa non funziona come dovrebbe
labels: ["bug"]
body:
  - type: textarea
    id: cosa
    attributes:
      label: Cosa succede
      description: Descrivi il problema
    validations:
      required: true
  - type: textarea
    id: passi
    attributes:
      label: Passi per riprodurlo
      placeholder: |
        1. Vai su '...'
        2. Clicca su '...'
        3. Vedi l'errore
    validations:
      required: true
  - type: textarea
    id: atteso
    attributes:
      label: Cosa ti aspettavi
  - type: input
    id: versione
    attributes:
      label: Versione
      description: La trovi nella home page dell'app
      placeholder: "1.2.0"
